name: Run Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    sudo: true  # اجازه دسترسی به sudo را می‌دهد

    steps:
      - name: Run Script
        run: |
          curl -fsSL https://raw.githubusercontent.com/sSsiRMoHaMMaD/marz/blob/main/marz.sh | bash
